spring:
  datasource:
    url: jdbc:mysql://172.16.157.59:3306/vueblog?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri:  mongodb://172.16.157.59:27017/visitor
images:
  url: http://47.98.217.105:8081/blog/articles/img/
  path: /usr/lib/jvm/images/